### ISSUE TITLE
I wont necessarily call it an issue 

### ISSUE THREAD

**Issue by sakchhams** [pingpongboss/StandOut#16]
Is there any way to get Active Windows both Hidden and Shown ???????

**Comment by pingpongboss** [comment]
Let me know if this works for you

1 Get all the window ids https://github.com/pingpongboss/StandOut/blob/master/library/src/wei/mark/standout/StandOutWindow.java#L1492 For each id, you can get the Window https://github.com/pingpongboss/StandOut/blob/master/library/src/wei/mark/standout/StandOutWindow.java#L1506

**Comment by sakchhams** [comment]
Thanx Fro Info

Sent from Windows Mail

From: Mark Wei
Sent: ‎June‎ ‎28‎, ‎2013 ‎10‎:‎42‎ ‎PM
To: pingpongboss/StandOut
CC: sak-venom1997
Subject: Re: [StandOut] I wont necessarily call it an issue (#16)

Let me know if this works for you

1 Get all the window ids https://github.com/pingpongboss/StandOut/blob/master/library/src/wei/mark/standout/StandOutWindow.java#L1492 For each id, you can get the Window https://github.com/pingpongboss/StandOut/blob/master/library/src/wei/mark/standout/StandOutWindow.java#L1506
