### ISSUE TITLE
Android Studio with Gradle build tools support 

### ISSUE THREAD

**Issue by sukso96100** [pingpongboss/StandOut#19]
Do you have any plans to support Android Studio that uses grable build tool officialy?
I have some trouble setting up this library in Android Studio

**Comment by pingpongboss** [comment]
Sorry, no plans for that.

Mark Wei · Software Engineer, Android Gmail Team · markwei@gmail.com ·
(714) 408-4066

**Comment by gw0** [comment]
Just import the project `example` (e.g. as `app`) and than import module `library` (e.g. as `standout`). Make a few minor tweaks and it will work.
