### ISSUE TITLE
NullPointerException at FloatingFolder.onReceiveData(FloatingFolder.java:219)

### ISSUE THREAD

**Issue by ghost** [pingpongboss/StandOut#2]
Ok when i wanted to open the app the second time i got:

06-15 11:04:29.650: E/AndroidRuntime(13895): FATAL EXCEPTION: main
06-15 11:04:29.650: E/AndroidRuntime(13895): java.lang.RuntimeException: Unable to start service wei.mark.example.floatingfolders.FloatingFolder@405241e8 with Intent { act=SEND_DATA cmp=wei.mark.example/.floatingfolders.FloatingFolder (has extras) }: java.lang.NullPointerException
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2338)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.app.ActivityThread.access$2800(ActivityThread.java:132)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1106)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.os.Looper.loop(Looper.java:143)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.app.ActivityThread.main(ActivityThread.java:4196)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at java.lang.reflect.Method.invokeNative(Native Method)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at java.lang.reflect.Method.invoke(Method.java:507)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at dalvik.system.NativeStart.main(Native Method)
06-15 11:04:29.650: E/AndroidRuntime(13895): Caused by: java.lang.NullPointerException
06-15 11:04:29.650: E/AndroidRuntime(13895):    at wei.mark.example.floatingfolders.FloatingFolder.onReceiveData(FloatingFolder.java:219)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at wei.mark.standout.StandOutWindow.onStartCommand(StandOutWindow.java:505)
06-15 11:04:29.650: E/AndroidRuntime(13895):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2321)
06-15 11:04:29.650: E/AndroidRuntime(13895):    ... 10 more

**Comment by pingpongboss** [comment]
should be fixed in latest.
