### ISSUE TITLE
Preferred way of getting Activity or Context from StandOutWindow?

### ISSUE THREAD

**Issue by gw0** [pingpongboss/StandOut#23]
I am wondering what is the preferred way of getting the current Activity or Context object into StandOutWindow? Or the other way around, how to access the FrameView of StandOutWindow from the Activity?

Or did I do something wrong and there exists a development pattern that doesn't get you in such troubles?

**Comment by pingpongboss** [comment]
The StandOutWindow exists in a Service, not an Activity. If you need a
Context, you can use "this" while inside of StandOutWindow or your own
subclass.

From the Activity, you can't directly access the StandOut windows. You'll
want to use the #sendData pattern
https://github.com/pingpongboss/StandOut/blob/master/library/src/wei/mark/standout/StandOutWindow.java#L205

**Comment by gw0** [comment]
Thank you.
