### ISSUE TITLE
Put Extra in activity

### ISSUE THREAD

**Issue by malizadehq** [pingpongboss/StandOut#31]
Hi
How put string in activity before show float windows, like:

Bundle data = new Bundle();
data.putString("changedText", mapimg);
StandOutWindow.sendData(view.getContext(), WidgetsWindow.class, StandOutWindow.DEFAULT_ID, DATA_CHANGED_TEXT, data, SimpleWindow.class, 1);

This code show Null
Thanks

**Comment by tabish075** [comment]
this has been resolved? how'd you do it
